name: Node.js Package

on:
  push:
    branches: main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "main"
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm test
      - uses: MeilCli/bump-release-action@v1.5.0
        with:
          config_path: ".github/bump.yml"
          github_token: ${{secrets.GITHUB_TOKEN}}

  merge-back-to-develop:
    needs: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "main"
      - name: Merge back to develop
        run: |
          git fetch --unshallow
          git checkout develop
          git pull
          git merge main
          git push
