name: Node.js Package

on:
  workflow_dispatch:
    inputs:
      bump:
        description: "bump type, major or minor or patch or empty string"
        default: ""
      dry_run:
        description: "dry run, true or false"
        default: "false"
      draft:
        description: "draft, true or false"
        default: "false"
      pre_release:
        description: "pre release, true or false"
        default: "false"

  release:
    types: [created]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm run test
      - uses: MeilCli/bump-release-action@v1
        with:
          config_path: ".github/bump.yml"

        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
