name: Node.js Package

on:
  pull_request:
    branches: main

jobs:
  validate-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "main"
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm test

  update-version:
    needs: validate-tests
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v3"
        with:
          ref: "main"

      - name: "Automated Version Bump"
        id: bump_version
        uses: "phips28/gh-action-bump-version@v9.1.0"
        with:
          tag-prefix: "v"
          target-branch: "main"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Changelog
        id: github_release
        uses: jaywcjlove/changelog-generator@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Output changelog"
        env:
          CHANGELOG: ${{ steps.github_release.outputs.changelog }}
        run: echo "$CHANGELOG"

      - name: Create Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          body: ${{steps.github_release.outputs.changelog}}
          tag_name: ${{steps.bump_version.outputs.newTag }}

  merge-back-to-develop:
    needs: update-version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "main"
      - name: Merge back to develop
        run: |
          git fetch --unshallow
          git checkout develop
          git pull
          git merge main
          git push
