name: Node.js Package

on:
  pull_request:
    branches: main

jobs:
  validate-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "main"
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm test

  update-version:
    needs: validate-tests
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v3"
        with:
          ref: "main"
      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@v9.1.0"
        with:
          tag-prefix: "v"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: update-version
    runs-on: ubuntu-latest
    steps:
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          body: ${{steps.github_release.outputs.changelog}}
